name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '42 4 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has been closed because it is stale. It can be reopened when work resumes.'
        stale-pr-message: 'This PR has been closed because it is stale. It can be reopened when work resumes.'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
